---
title: "Title Here"
author: "430189999"
date: "data here"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    theme: "yeti"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###Domain Information
blah blah blah
```{r load_libraries,results="hide",message=FALSE}
##loading data
library(readxl)
require(dplyr)
require(tibble)
require(ggplot2)
require(stringr)
require(naniar)
library(readr)
```
##Data Dictionary


```{r}
All_sample_data <- read_csv("Uni/AMED3002/assessment 1/All_sample_data.csv")
df <- All_sample_data
count(df$P)
```

###Cleaning

```{r clean_data,results="hide",message=FALSE,warning=FALSE}

```

```{r,results="hide",message=FALSE}
```

##Tab Heading {.tabset .tabset-fade .tabset-pills}

Plots

###Tab1

```{r exploration_plotting}
#ggplot(df, aes(x=df$`Age at Dx (years)`, fill = df$`Age at Dx (years)`)) +
#  geom_bar(position = "dodge2") +
#    labs(title = "Age/Gender distribution",  fill = "Age", x = "Gender", y = "Count")
```

###Tab 2

```{r}
#both distrbutions are approx normal
#ggplot(df, aes(x=df$Gender, fill = df$`Age at Dx (years)`)) +
#  geom_bar(position = "dodge2") +
#    labs(title = "Age/Gender distribtion",  fill = "Age", x = "Gender", y = "Count")
```

###Tab 3


```{r}
#ggplot(df, aes(x=df$Race, fill = df$`Age at Dx (years)`)) +
#  geom_bar(position = "dodge2") +
#    labs(title = "Race/Gender included in study", x = "Gender", y = "Count", fill = "Age")
```

##Tab Section 2{.tabset .tabset-fade .tabset-pills}

###Tab 2.1

```{r}
#ggplot(df, aes(x = df$Gender, y = df$`Survival (months)`, fill = df$Gender)) + geom_boxplot() +
#facet_wrap(~ df$Disease, ncol = 50) +
#  labs(title = "Survival time between men and women, by disease", x = "Gender", y = "Survival Time")
```

###Tab 2.2

```{r}
##ggplot(df,aes(x = df$`Age at Dx (years)`, y = df$`Survival (months)`, colour = df$Disease)) +
#  geom_point() +
#  geom_jitter(height = 0.05) +
#  labs(colour = "Disease", y="Months Survived", x="Age", title="Comparing Age and Survival by Disease type") +
#  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10))
```


###Tab 2.3

```{r}
#ggplot(df,aes(x=df$`Age at Dx (years)`, y=df$`Survival (months)`, colour = df$`OnStudy Therapy Radiation Type`, #shape = df$`OnStudy Therapy Chemo Agent Name`)) +
#  geom_point() +
#  facet_wrap(~df$Disease) +
#  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7)) +
#  labs(shape = "patient had chemo", colour = "patient had RT", y="Age at diagnosis",x="Months survived" ,title = "Comparing age and survival time by treatment type, between diseases")
```

##Analysis

```{r analysis}

```

```{r}
```

```{r}

```




